services:
  - type: web
    name: email-agentic-workflow # Updated name to reflect your app
    runtime: ruby # This app is written in Ruby
    plan: free # Ensure you're on the free plan
    buildCommand: "./bin/render-build.sh" # Customize your build command if needed
    startCommand: "./bin/render-start.sh"
    envVars: 
      # Render-provided ENV variables
      - key: SECRET_KEY_BASE
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: db
          property: connectionString
      - key: WEB_CONCURRENCY
        value: 2
      
      # Application-specific ENV variables
      - key: OPENAI_API_KEY
        sync: false # Add your OpenAI API key in Render's dashboard for security
      - key: GOOGLE_APPLICATION_CREDENTIALS
        value: /path/to/email-agentic-workflow-622fe974ccd1.json
      - key: GMAIL_API_SCOPES
        value: "https://www.googleapis.com/auth/gmail.readonly,https://www.googleapis.com/auth/gmail.modify"
      - key: RAILS_ENV
        value: production
      - key: RACK_ENV
        value: production
      
databases: 
  - name: db
    plan: free
    ipAllowList: [] 
